name: build
on:
  pull_request:
    branches: 
     - main
  push:
    branches: 
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - run: npm install
      # Fix FATAL ERROR - JavaScript heap out of memory
      - run: npm install -g increase-memory-limit && increase-memory-limit
      - run: npm run build
