name: check
on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main
jobs:
  LinkCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: "1.16.6"
      - name: Check Link
        run: make check-link

  # Lints Pull Request commits with commitlint.
  #
  # Rules can be referenced: 
  # https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional
  # CommitLint:
  #   name: Commit Lint
  #   runs-on: ubuntu-latest
  #   if: contains(fromJSON('["pull_request"]'), github.event_name)
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - uses: wagoid/commitlint-github-action@v5

  # LicenseCheck:
  #   name: License Check
  #   runs-on: ubuntu-latest
  #   env:
  #     TERM: xterm
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - uses: apache/skywalking-eyes@main

  # The TruffleHog OSS Github Action can be used to scan a range of commits for leaked credentials. The action will fail if any results are found.
  # More see: https://github.com/marketplace/actions/trufflehog-oss
  SecretScan:
    name: Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --json
