name: build-and-deploy
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    types:
    - closed
jobs:
  deploy:
    if: (github.event_name == 'push') || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - run: npm install
      - run: npm run build

      - name: Deploy kcl-lang/kcl-lang.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          external_repository: kcl-lang/kcl-lang.github.io
          publish_dir: ./build
          publish_branch: main
