name: example-e2e-test
on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main
jobs:
  example-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Install Script
        run: static/script/install.sh
      - name: Check KCL run
        shell: bash -ieo pipefail {0}
        run: kcl hello.k

      - name: Example tests
        shell: bash -ieo pipefail {0}
        run: ./examples/test.sh
