name: example-e2e-test
on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main
jobs:
  example-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Install Script
        run: static/script/install.sh
      - name: Check KCL run
        shell: bash -ieo pipefail {0}
        run: kcl ./static/stack/main.k

      - uses: actions/setup-go@v1
        with:
          go-version: "1.19"

      - name: kpm Installation
        run: go install kcl-lang.io/kpm@main

      - name: Example tests
        shell: bash -ieo pipefail {0}
        run: PATH=$PATH:$HOME/go/bin ./examples/test.sh
