name: script-kusion
on:
  push:
    branches: 
     - main
jobs:
  check-kusion-script-install:
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Check Install Script
        run: curl https://www.kusionstack.io/scripts/install.sh | sh
      - name: Check Kusion run
        shell: bash -leo pipefail {0}
        run: |
          sudo kusion version
          sudo kusion build -w static/stack -o stdout
          cd static/stack && sudo kusion build
      - name: Uninstall Kusion
        run: curl https://www.kusionstack.io/scripts/uninstall.sh | sh

  check-kusion-brew-install:
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Check Brew Installation
        working-directory: .
        run: |
          brew install KusionStack/tap/kusion
          echo "brew installed successfully"
          kusion version
          kusion build -w static/stack -o stdout
          cd static/stack && kusion build
          brew uninstall KusionStack/tap/kusion

  check-kusion-go-install:
    strategy:
      matrix:
        os: [macos-11, macos-12, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-go@v1
        with:
          go-version: "1.19"

      - name: Check Go Installation
        working-directory: .
        run: |
          go install kusionstack.io/kusion@main
          echo "go installed successfully"
          $HOME/go/bin/kusion version
          $HOME/go/bin/kusion build -w static/stack -o stdout
          cd static/stack && $HOME/go/bin/kusion build

  check-kusion-scoop-install:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Scoop Install
        shell: powershell
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop bucket add KusionStack https://github.com/KusionStack/scoop-bucket.git
          scoop install KusionStack/kusion
          mkdir C:\Users\runneradmin\go
          kusion build -w static/stack -o stdout
