name: link-check

on: ["push", "pull_request"]

jobs:
  check-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: "1.16.6"
      - name: Check Link
        run: make check-link
