name: script-kusion
on:
  pull_request:
    branches: 
     - main
  push:
    branches: 
     - main
jobs:
  check-brew:
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - name: Check Brew Installation
        run: |
          brew install KusionStack/tap/kusion
          echo "brew installed successfully"
          kusion compile ./static/samples/hello.k

  check-go:
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-go@v1
        with:
          go-version: "1.18"

      - name: Check Go Installation
        run: |
          go install kusionstack.io/kusion@latest
          echo "go installed successfully"
          $HOME/go/bin/kusion compile ./static/samples/hello.k
