name: script-kusion
on:
  pull_request:
    branches: 
     - main
  push:
    branches: 
     - main
jobs:
  check-brew:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Check Brew Installation
        run: brew install KusionStack/tap/kusion && kusion compile ./static/samples.k

  check-go:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-go@v1
        with:
          go-version: "1.17"

      - name: Check Go Installation
        run: go install kusionstack.io/kusion@latest && $HOME/go/bin/kusion compile ./static/samples.k
