name: script-kusion
on:
  push:
    branches: 
     - main
jobs:
  check-kusion-brew-install:
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - name: Check Brew Installation
        working-directory: .
        run: |
          brew install KusionStack/tap/kusion
          echo "brew installed successfully"
          kusion version
          kusion compile hello.k

  check-kusion-go-install:
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-go@v1
        with:
          go-version: "1.18"

      - name: Check Go Installation
        working-directory: .
        run: |
          go install kusionstack.io/kusion@latest
          echo "go installed successfully"
          $HOME/go/bin/kusion version
          $HOME/go/bin/kusion compile hello.k

  check-kclvm-go-install:
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-go@v1
        with:
          go-version: "1.18"

      - name: Check Go Installation
        working-directory: .
        run: |
          go install kusionstack.io/kclvm-go/cmds/kcl-go@main
          echo "go installed successfully"
          $HOME/go/bin/kcl-go kcl hello.k
